name: diff
description: bash like diff in javascript
author: Thibault Croisier

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  new_file:
    description: The new file to diff
    required: true
  old_file:
    description: The old file used for the diff
    required: true

# Define your outputs here.
outputs:
  diff:
    description: The diff result

runs:
  using: node20
  main: dist/index.js
